apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: scale-to-zero
rules:
- apiGroups: [""]
  resources: ["services"]
  verbs: ["list", "get", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "patch", "list", "watch"]
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: scale-to-zero
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: scale-to-zero
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: scale-to-zero
subjects:
- kind: ServiceAccount
  name: scale-to-zero
  namespace: default
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: scale-to-zero
spec:
  selector:
    matchLabels:
      app: scale-to-zero
  template:
    metadata:
      labels:
        app: scale-to-zero
    spec:
      serviceAccountName: scale-to-zero
      hostNetwork: true
      hostPID: true
      containers:
      - name: scale-to-zero
        image: supiri/scale-to-zero:latest-arm
        securityContext:
          privileged: true
        env:
        - name: RUST_LOG
          value: info
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.25.3
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
  annotations:
    scale-to-zero.isala.me/scale-down-time: "10" # 10 seconds
    scale-to-zero.isala.me/reference: "deployment/nginx"
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: curl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: curl
  template:
    metadata:
      labels:
        app: curl
    spec:
      containers:
      - name: curl-container
        image: curlimages/curl
        command: ["/bin/sh"]
        args: ["-c", "sleep 1000000000"]
